/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPckg;

import java.util.Calendar;
import java.util.GregorianCalendar;
import javafx.scene.paint.Color;

/**
 *
 * @author Joni
 */
public class KelloGUI extends javax.swing.JFrame {

    /**
     * Creates new form KelloGUI
     */
    public KelloGUI() {
        
        initComponents();
        
        new Thread() {
            public void run() {
                while(true) {
                    Calendar kalenteri = new GregorianCalendar();
                    
                    int tunti = kalenteri.get(Calendar.HOUR);
                    // Lisää nollan numeron eteen, mikäli minuutteja on alle 10
                    String minuutti = (String.format("%02d", kalenteri.get(Calendar.MINUTE)));
                    // Lisää nollan numeron eteen, mikäli sekunteja on alle 10
                    String sekunti = (String.format("%02d", kalenteri.get(Calendar.SECOND)));
                    int amPm = kalenteri.get(Calendar.AM_PM);
                    int pvm = kalenteri.get(Calendar.DAY_OF_MONTH);
                    int kk = kalenteri.get(Calendar.MONTH);
                    int vv = kalenteri.get(Calendar.YEAR);
                    
                    String paivaTaiYo;
                    
                    if (amPm == 1) {
                        paivaTaiYo = "PM";
                    } else {
                        paivaTaiYo = "AM";
                    }

                    String aika = tunti + ":" + minuutti + ":" + sekunti + " " + paivaTaiYo;
                    String paivamaara = pvm + "." + kk + "." + vv;
                    
                    kelloLabel.setText(aika);
                    pvmLabel.setText(paivamaara);
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kello = new javax.swing.JPanel();
        kelloLabel = new javax.swing.JLabel();
        pvmLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Kello.setBackground(new java.awt.Color(9, 8, 8));

        kelloLabel.setFont(new java.awt.Font("Radioland", 0, 36)); // NOI18N
        kelloLabel.setForeground(new java.awt.Color(215, 13, 13));
        kelloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kelloLabel.setToolTipText(null);

        pvmLabel.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 36)); // NOI18N
        pvmLabel.setForeground(new java.awt.Color(54, 82, 82));
        pvmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout KelloLayout = new javax.swing.GroupLayout(Kello);
        Kello.setLayout(KelloLayout);
        KelloLayout.setHorizontalGroup(
            KelloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KelloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pvmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(kelloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        KelloLayout.setVerticalGroup(
            KelloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KelloLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(kelloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pvmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Kello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Kello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelloGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelloGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelloGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelloGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelloGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Kello;
    private javax.swing.JLabel kelloLabel;
    private javax.swing.JLabel pvmLabel;
    // End of variables declaration//GEN-END:variables
}
